# permissions for end users to edit pdfdocs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pdfdoc-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pdfdoccrdoperator
    app.kubernetes.io/part-of: pdfdoccrdoperator
    app.kubernetes.io/managed-by: kustomize
  name: pdfdoc-editor-role
rules:
- apiGroups:
  - customtools.janasabuj.github.io
  resources:
  - pdfdocs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - customtools.janasabuj.github.io
  resources:
  - pdfdocs/status
  verbs:
  - get
