apiVersion: customtools.janasabuj.github.io/v1
kind: PdfDoc
metadata:
  labels:
    app.kubernetes.io/name: pdfdoc
    app.kubernetes.io/instance: pdfdoc-sample
    app.kubernetes.io/part-of: pdfdoccrdoperator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: pdfdoccrdoperator
  name: pdfdoc-sample
spec:
  # TODO(user): Add fields here
  docName: sabuj-document
  rawText: |
    # Shakespeare
    ---
    > Shall I compare thee to a summer's day?
    > Thou art more lovely and more temperate:
    > Rough winds do shake the darling buds of May,
    > And summer's lease hath all too short a date:
    > Sometime too hot the eye of heaven shines,
    > And often is his gold complexion dimmed;
    > And every fair from fair sometime declines,
    > By chance, or nature's changing course untrimmed:
    > But thy eternal summer shall not fade
    > Nor lose possession of that fair thou owest;
    > Nor shall Death brag thou wanderest in his shade,
    > When in eternal lines to time thou growest:
    > So long as men can breathe or eyes can see,
    > So long lives this, and this gives life to thee.
    ---
    THE END

