---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - customtools.janasabuj.github.io
  resources:
  - pdfdocs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - customtools.janasabuj.github.io
  resources:
  - pdfdocs/finalizers
  verbs:
  - update
- apiGroups:
  - customtools.janasabuj.github.io
  resources:
  - pdfdocs/status
  verbs:
  - get
  - patch
  - update
